# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1379397433);
user_pref("app.update.lastUpdateTime.background-update-timer", 1379397277);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1379397553);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1379396395);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1379401536);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1379396515);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 13);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 863);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.ssl_override_behavior", 1);
user_pref("browser.startup.homepage_override.buildID", "20130814063812");
user_pref("browser.startup.homepage_override.mstone", "23.0.1");
user_pref("browser.taskbar.lastgroupid", "E7CF176E110C211B");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1379482794552");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1379396394552");
user_pref("datareporting.sessions.current.activeTicks", 2);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 718);
user_pref("datareporting.sessions.current.main", 76);
user_pref("datareporting.sessions.current.sessionRestored", 736);
user_pref("datareporting.sessions.current.startTime", "1379492943061");
user_pref("datareporting.sessions.current.totalTime", 7);
user_pref("datareporting.sessions.currentIndex", 9);
user_pref("datareporting.sessions.previous.0", "{\"s\":1379396393701,\"a\":16,\"t\":171,\"c\":true,\"m\":77,\"fp\":7300,\"sr\":3372}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1379397156411,\"a\":19,\"t\":153,\"c\":true,\"m\":77,\"fp\":737,\"sr\":755}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1379397312930,\"a\":18,\"t\":693,\"c\":true,\"m\":64,\"fp\":699,\"sr\":719}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1379398009290,\"a\":1,\"t\":5,\"c\":true,\"m\":75,\"fp\":702,\"sr\":720}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1379398052848,\"a\":2,\"t\":9,\"c\":true,\"m\":75,\"fp\":703,\"sr\":722}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1379401470924,\"a\":5,\"t\":26,\"c\":true,\"m\":76,\"fp\":768,\"sr\":4456}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1379414051743,\"a\":5,\"t\":23,\"c\":true,\"m\":45,\"fp\":1135,\"sr\":1153}");
user_pref("datareporting.sessions.previous.7", "{\"s\":1379414080845,\"a\":3,\"t\":11,\"c\":true,\"m\":46,\"fp\":725,\"sr\":741}");
user_pref("datareporting.sessions.previous.8", "{\"s\":1379414116596,\"a\":12,\"t\":60,\"c\":true,\"m\":76,\"fp\":724,\"sr\":744}");
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:23.0.1");
user_pref("extensions.enabledItems", "fiddlerhook@fiddler2.com:2.3.7.4,{aa84ce40-4253-a00a-8cd6-0800200f9a66}:3.7.2.1043,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6.23");
user_pref("extensions.installCache", "[{\"name\":\"winreg-app-global\",\"addons\":{\"fiddlerhook@fiddler2.com\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Fiddler2\\\\FiddlerHook\",\"mtime\":1323960974984,\"rdfTime\":1323028208000},\"FFPDFArchitectConverter@pdfarchitect.com\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\PDF Architect\\\\FFPDFArchitectExt\",\"mtime\":1359007393310,\"rdfTime\":1357741440000},\"{aa84ce40-4253-a00a-8cd6-0800200f9a66}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Estonian ID Card\\\\Firefox PKCS11 Loader\",\"mtime\":1379057754636,\"rdfTime\":1376575024000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1379401789777,\"rdfTime\":1376493606000}}}]");
user_pref("extensions.lastAppVersion", "23.0.1");
user_pref("extensions.lastPlatformVersion", "23.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.update.notifyUser", false);
user_pref("gecko.buildID", "20130814063812");
user_pref("gecko.mstone", "23.0.1");
user_pref("gfx.direct3d.last_used_feature_level_idx", 0);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.type", 0);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("plugin.state.java", 0);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1379492943);
user_pref("toolkit.telemetry.previousBuildID", "20130814063812");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1381988405);
user_pref("webdriver_assume_untrusted_issuer", false);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
